version: '3.8'

services:
  resolver-dns:
    image: ghcr.io/eabruzzese/docker-resolver
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "127.0.0.1:53:53/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  resolver-traefik:
    image: traefik:v3.0
    command:
      # Allow insecure requests to the Traefik API.
      - "--api.insecure=true"
      # Expose all containers locally by default.
      - "--providers.docker"
      - "--providers.docker.exposedbydefault"
    ports:
      # All web traffic.
      - "127.0.0.1:80:80"
      # The traefik dashboard.
      - "127.0.0.1:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
